app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Название поста: ', validators=[DataRequired()])
    content = TextAreaField('Содержание поста: ', validators=[DataRequired()])
    submit = SubmitField('Опубликовать')

app/posts/__init__.py
from flask import Blueprint


posts = Blueprint('posts', __name__)

from . import views

app/posts/views.py
from . import posts
from flask import render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required
from .. import db
from ..models import Post
from ..posts.forms import PostForm


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Пост успешно создан', 'success')
        return redirect(url_for('main.index'))
    return render_template('create_post.html', title='Новый пост', form=form, legend='Новый пост')


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Ваш пост успешно изменен', 'success')
        return redirect(url_for('posts.post', post_id=post_id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Изменение поста', form=form, legend='Изменение поста')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Пост удален', 'success')
    return redirect(url_for('main.index'))

app/templates/about.html
{% extends 'base.html' %}

{% block content %}
  <h1>О блоге</h1>
{% endblock content %} 

app/templates/account.html
{% extends 'base.html' %}

{% block content %}
  <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ image_file }}">
      <div class="media-body">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>
      </div>
    </div>
    <form method="POST" action="" enctype="multipart/form-data">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-2">Информация о профиле</legend>

        <div class="form-group mb-2">
          {{ form.username.label(class="form-control-label") }}
          {% if form.username.errors %}
            {{ form.username(class="form-control-label is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.username.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.username(class="form-control form-control-lg") }}
          {% endif %}
        </div>
  
        <div class="form-group mb-3">
          {{ form.email.label(class="form-control-label") }}
          {% if form.email.errors %}
            {{ form.email(class="form-control-label is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group mb-2">
          {{ form.picture.label() }}
            {{ form.picture(class="form-control-file") }}
          {% if form.picture.errors %}
            {% for error in form.picture.errors %}
              <br><span class="text-danger">{{ error }}</span></br>
            {% endfor %}
          {% endif %}
        </div>

      </fieldset>
      <div class="form-group pt-2">
        {{ form.submit(class="btn btn-outline-secondary") }}
      </div>
    </form>
  </div>
{% endblock content %} 

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" 
        crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
  <title>
    {% if title %}
      Блог - {{ title }}
    {% else %} 
      Блог
    {% endif %}
  </title>
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" 
          integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" 
          crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" 
          integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" 
          crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" 
          integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" 
          crossorigin="anonymous"></script>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="#">Блог</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" 
                aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.index') }}">Главная</a>
            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">О блоге</a>
          </div>
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">Создать пост</a>
              <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Личный кабинет</a>
              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Выйти</a>
            {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Войти</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Зарегистрироваться</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% with messages = get_flashed_messages(with_categories=True) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock content %}
      </div>
      <div class="col-md-4">
        <div class="content-section">
          <p class='text-muted'>
            <ul class="list-group">
              <li class="list-group-item list-group-item-light">Последние сообщения</li>
              <li class="list-group-item list-group-item-light">Объявления</li>
              <li class="list-group-item list-group-item-light">Календарь</li>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </main>
</body>
</html>

app/templates/create_post.html
{% extends 'base.html' %}

{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">{{ legend }}</legend>

        <div class="form-group">
          {{ form.title.label(class="form-control-label") }}
          {% if form.title.errors %}
            {{ form.title(class="form-control-label is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.title.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
           {{ form.title(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group pt-2">
          {{ form.content.label(class="form-control-label") }}
          {% if form.content.errors %}
            {{ form.content(class="form-control-label is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.content.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
           {{ form.content(class="form-control form-control-lg") }}
          {% endif %}
        </div>

      </fieldset>
      <div class="form-group ml-3 pt-2">
        {{ form.submit(class="btn btn-outline-secondary") }}
      </div>
    </form>
  </div>
{% endblock content %} 

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
  {% for post in posts.items %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ url_for('static', filename='img/' + post.author.image_file) }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
    </article>
  {% endfor %}
    {% for num_page in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if num_page %}
        {% if posts.page == num_page %}
          <a class="btn btn-secondary btn-sm mb-4" href="{{ url_for('main.index', page=num_page) }}">{{ num_page }}</a>
        {% else %}
          <a class="btn btn-outline-secondary btn-sm mb-4" href="{{ url_for('main.index', page=num_page) }}">{{ num_page }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
  {% endfor %}

{% endblock content %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Авторизация</legend>

        <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {% if form.email.errors %}
            {{ form.email(class="form-control-label is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
           {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group pt-2">
          {{ form.password.label(class="form-control-label") }}
          {% if form.password.errors %}
            {{ form.password(class="form-control-label is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
           {{ form.password(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-check pt-2">
          {{ form.remember(class="form-check-input") }}
          {{ form.remember.label(class="form-check-label") }}
        </div>

      </fieldset>
      <div class="form-group ml-3 pt-2">
        {{ form.submit(class="btn btn-outline-secondary") }}
      </div>
      <small class="text-muted">
        <a href="{{ url_for('users.reset_request') }}">Забыли пароль?</a>         
      </small>
    </form>
  </div>
  <div class="border-top pt-1">
    <small class="text-muted">
      Нет учетной записи? <a class="ml-2" href="{{ url_for('users.register') }}">Создать аккаунт</a>
    </small>
  </div>
{% endblock content %} 

app/templates/post.html
{% extends 'base.html' %}

{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='img/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Изменить</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Удалить</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>

  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Вы действительно хотите удалить этот пост?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Не удалять</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Удалить">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

app/templates/register.html
{% extends 'base.html' %}

{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Заполните форму регистрации</legend>

        <div class="form-group">
          {{ form.username.label(class="form-control-label") }}
          {% if form.username.errors %}
            {{ form.username(class="form-control-label is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.username.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
           {{ form.username(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group pt-2">
          {{ form.email.label(class="form-control-label") }}
          {% if form.email.errors %}
            {{ form.email(class="form-control-label is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
           {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group pt-2">
          {{ form.password.label(class="form-control-label") }}
          {% if form.password.errors %}
            {{ form.password(class="form-control-label is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
           {{ form.password(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group pt-2">
          {{ form.confirm_password.label(class="form-control-label") }}
          {% if form.confirm_password.errors %}
            {{ form.confirm_password(class="form-control-label is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.confirm_password.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
           {{ form.confirm_password(class="form-control form-control-lg") }}
          {% endif %}
        </div>

      </fieldset>
      <div class="form-group pt-3">
        {{ form.submit(class="btn btn-outline-secondary") }}
      </div>
    </form>
  </div>
  <div class="border-top pt-1">
    <small class="text-muted">
      Есть учетная запись? <a class="ml-2" href="{{ url_for('users.login') }}">Войти</a>
    </small>
  </div>
{% endblock content %}

app/templates/reset_request.html
{% extends 'base.html' %}

{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Сброс пароля</legend>

        <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {% if form.email.errors %}
            {{ form.email(class="form-control-label is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
           {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>

      </fieldset>
      <div class="form-group ml-3 pt-2">
        {{ form.submit(class="btn btn-outline-secondary") }}
      </div>
    </form>
  </div>

{% endblock content %}

app/templates/reset_token.html
{% extends 'base.html' %}

{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Сброс пароля</legend>

        <div class="form-group">
          {{ form.password.label(class="form-control-label") }}
          {% if form.password.errors %}
            {{ form.password(class="form-control-label is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
           {{ form.password(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group">
            {{ form.confirm_password.label(class="form-control-label") }}
            {% if form.confirm_password.errors %}
              {{ form.confirm_password(class="form-control-label is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.confirm_password.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
             {{ form.confirm_password(class="form-control form-control-lg") }}
            {% endif %}
          </div>

      </fieldset>
      <div class="form-group ml-3 pt-2">
        {{ form.submit(class="btn btn-outline-secondary") }}
      </div>
    </form>
  </div>

{% endblock content %}

app/templates/user_posts.html
{% extends 'base.html' %}

{% block content %}
  <h2 class="mb-3">Посты {{ user.username }} ({{ posts.total }})</h2>
  {% for post in posts.items %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ url_for('static', filename='img/' + post.author.image_file) }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
    </article>
  {% endfor %}
    {% for num_page in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if num_page %}
        {% if posts.page == num_page %}
          <a class="btn btn-secondary btn-sm mb-4" href="{{ url_for('users.user_posts', username=user.username, page=num_page) }}">{{ num_page }}</a>
        {% else %}
          <a class="btn btn-outline-secondary btn-sm mb-4" href="{{ url_for('users.user_posts', username=user.username, page=num_page) }}">{{ num_page }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
  {% endfor %}

{% endblock content %}